### ISSUE TITLE
The taskbar icon is not visible on KDE Plasma

### ISSUE THREAD

**Issue by jclsn** [mikepruett3/homeassistant-desktop#1]
The headline says it all.  Would be great if this could be fixed. Not sure if it is a Plasma-only issue, but I can't say for the desktop environments.

**Comment by mikepruett3** [comment]
Sorry, I have only tried on Windows, and Gnome. I will have to spin up a VM with KDE Plasma installed. Which distro are you using?

**Comment by jclsn** [comment]
Arch Linux

**Comment by mikepruett3** [comment]
Try it now, and let me know if it worked

**Comment by jclsn** [comment]
Yes. works
