### ISSUE TITLE
Live Camera Previews

### ISSUE THREAD

**Issue by awptechnologies** [mikepruett3/homeassistant-desktop#4]
I used this just to try it. I use frigate form HACS in my homeassistant. It shows a live preview of all my cameras. The page with this takes forever to load. If i switch back and forth between my other dashboards everything is good. As soon as i click on the dashboard with the frigate integration it fails to reload. This happens with or without hardware acceleration.

**Comment by mikepruett3** [comment]
Electron's IPC processes do not handle streaming video very well. I will have to look and see if there is anything I can do to improve it, but I have a similar problem loading feeds from my Amcrest cameras. Even with 640x480 RTSP streams, it takes a few seconds to load.

**Comment by awptechnologies** [comment]
It seems to have fixed itself. No issues now.
